# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [3]:
# The code goes here
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [4]:
#Code comes here
arr1 = np.repeat(1,10)
arr2 = np.arange(1, 21, 1, dtype="int")
arr3 = np.ones((5, 5), dtype="int")



print(arr1)
print(arr2)
print(arr3)

[1 1 1 1 1 1 1 1 1 1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [45]:
# Code comes here
arr1=np.random.randn(3,3,3)
print(arr1)
print(arr1.shape)
print(arr1.size)
arr1b = arr1.reshape(27)
print(arr1b)

[[[ 0.35192359  0.95053009  0.39135393]
  [-1.33023729 -0.84700362 -0.84348854]
  [ 1.8798534  -0.7722428  -2.39786437]]

 [[ 0.39238912  0.09190322  0.27704516]
  [-1.24846463  1.43241294  0.28770357]
  [-1.14128709  0.37718282 -0.42515936]]

 [[-1.11590369  1.6696159  -1.82798047]
  [ 0.53688798  0.41014673 -0.26234469]
  [ 0.48100642  0.21024294  0.00874983]]]
(3, 3, 3)
27
[ 0.35192359  0.95053009  0.39135393 -1.33023729 -0.84700362 -0.84348854
  1.8798534  -0.7722428  -2.39786437  0.39238912  0.09190322  0.27704516
 -1.24846463  1.43241294  0.28770357 -1.14128709  0.37718282 -0.42515936
 -1.11590369  1.6696159  -1.82798047  0.53688798  0.41014673 -0.26234469
  0.48100642  0.21024294  0.00874983]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [46]:
# Code comes here
arr1 = np.linspace(1, 10, 20, dtype="int")
print(arr1)

[ 1  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [5]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [49]:
20

20

In [66]:
#Code goes here
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [ ]:
# Code come here


```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
# Code comes here

## 2.5 

Calculate the sum of all the numbers in `a`.

In [70]:
# Code comes here
total = 0
print(a)
print(" ")
for item in a:
    total += item
print(total)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
 
[55 60 65 70 75]


## 2.6 

Calculate the sum of each row in `a`.

In [ ]:
# Code comes here

## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [ ]:
# Code comes here

# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [1]:
# Codes comes here
import pandas as pd


## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [5]:
# Code comes here
df = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv", sep=",", header=0, encoding="ISO-8859-1")
print(df.head(10))


     country             food_category  consumption  co2_emmission
0  Argentina                      Pork        10.51          37.20
1  Argentina                   Poultry        38.66          41.53
2  Argentina                      Beef        55.48        1712.00
3  Argentina               Lamb & Goat         1.56          54.63
4  Argentina                      Fish         4.36           6.96
5  Argentina                      Eggs        11.39          10.46
6  Argentina        Milk - inc. cheese       195.08         277.87
7  Argentina  Wheat and Wheat Products       103.11          19.66
8  Argentina                      Rice         8.77          11.22
9  Argentina                  Soybeans         0.00           0.00


## 2.10 

How many rows and columns are there in the dataframe?

In [6]:
#Code comes here
print(df.count)

<bound method DataFrame.count of          country             food_category  consumption  co2_emmission
0      Argentina                      Pork        10.51          37.20
1      Argentina                   Poultry        38.66          41.53
2      Argentina                      Beef        55.48        1712.00
3      Argentina               Lamb & Goat         1.56          54.63
4      Argentina                      Fish         4.36           6.96
...          ...                       ...          ...            ...
1425  Bangladesh        Milk - inc. cheese        21.91          31.21
1426  Bangladesh  Wheat and Wheat Products        17.47           3.33
1427  Bangladesh                      Rice       171.73         219.76
1428  Bangladesh                  Soybeans         0.61           0.27
1429  Bangladesh   Nuts inc. Peanut Butter         0.72           1.27

[1430 rows x 4 columns]>


## 2.11

What is the mean `co2_emission` of the whole dataset?

In [12]:
# Code comes here
df["co2_emission"].mean()


KeyError: 'co2_emission'

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [ ]:
# Code comes here

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [ ]:
#code comes here

## 2.14

Which country consumes the least amount of beef per person per year?


In [ ]:
# code comes here

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [ ]:
# code comes here

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [ ]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.