# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [24]:
# The code goes here
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [25]:
#Code comes here
arr1 = np.repeat(1,10)
arr2 = np.arange(1, 21, 1, dtype="int")
arr3 = np.ones((5, 5), dtype="int")



print(arr1)
print(arr2)
print(arr3)

[1 1 1 1 1 1 1 1 1 1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [26]:
# Code comes here
arr1=np.random.randn(3,3,3)
print(arr1)
print(arr1.shape)
print(arr1.size)
arr1b = arr1.reshape(27)
print(arr1b)

[[[-0.95809954  1.23255502  0.39305804]
  [ 0.07377218 -1.12269016  0.33457825]
  [ 0.61222267  0.17950119 -0.01362835]]

 [[ 1.36583908  0.96826358  1.65416814]
  [ 0.40463503  0.25597426 -2.71098081]
  [ 2.66794229  0.86147113 -0.86099672]]

 [[ 1.82544065 -0.84263096  0.82178981]
  [-0.66975981  2.27398368 -0.85674509]
  [ 0.12100363  2.01725852 -0.11166162]]]
(3, 3, 3)
27
[-0.95809954  1.23255502  0.39305804  0.07377218 -1.12269016  0.33457825
  0.61222267  0.17950119 -0.01362835  1.36583908  0.96826358  1.65416814
  0.40463503  0.25597426 -2.71098081  2.66794229  0.86147113 -0.86099672
  1.82544065 -0.84263096  0.82178981 -0.66975981  2.27398368 -0.85674509
  0.12100363  2.01725852 -0.11166162]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [27]:
# Code comes here
arr1 = np.linspace(1, 10, 20, dtype="int")
print(arr1)

[ 1  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [28]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [29]:
20

20

In [30]:
#Code goes here
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [31]:
# Code come here


```python
array([ 6,  7,  8,  9, 10])
```

In [32]:
# Code comes here

## 2.5 

Calculate the sum of all the numbers in `a`.

In [33]:
# Code comes here
total = 0
print(a)
print(" ")
for item in a:
    total += item
print(total)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
 
[55 60 65 70 75]


## 2.6 

Calculate the sum of each row in `a`.

In [35]:
# Code comes here
total = 0
for item in a:
    total += item
print(total)

[55 60 65 70 75]


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [ ]:
# Code comes here

# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [1]:
# Codes comes here
import pandas as pd


## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [15]:
# Code comes here
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"
df = pd.read_csv(url)
df


country             food_category  consumption  co2_emmission
0      Argentina                      Pork        10.51          37.20
1      Argentina                   Poultry        38.66          41.53
2      Argentina                      Beef        55.48        1712.00
3      Argentina               Lamb & Goat         1.56          54.63
4      Argentina                      Fish         4.36           6.96
...          ...                       ...          ...            ...
1425  Bangladesh        Milk - inc. cheese        21.91          31.21
1426  Bangladesh  Wheat and Wheat Products        17.47           3.33
1427  Bangladesh                      Rice       171.73         219.76
1428  Bangladesh                  Soybeans         0.61           0.27
1429  Bangladesh   Nuts inc. Peanut Butter         0.72           1.27

[1430 rows x 4 columns]

## 2.10 

How many rows and columns are there in the dataframe?

In [20]:
#Code comes here
print(df.shape)

(1430, 4)


## 2.11

What is the mean `co2_emission` of the whole dataset?

In [22]:
# Code comes here
df["co2_emission"].mean()


KeyError: 'co2_emission'

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [36]:
# Code comes here
df.iloc[df['co2_emmission'].idxmax()]
# df specifies the data frame
# iloc specifies indexing with intergers
# co2_emission specifies the column name
# returns a series with the index of the maximum value for the specified column

country          Argentina
food_category         Beef
consumption          55.48
co2_emmission       1712.0
Name: 2, dtype: object

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [37]:
#code comes here
df.query("co2_emission > 1000")

UndefinedVariableError: name 'co2_emission' is not defined

## 2.14

Which country consumes the least amount of beef per person per year?


In [ ]:
# code comes here

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [ ]:
# code comes here

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [ ]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.